### ISSUE TITLE
http.CloseNotifier unimplemented?

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [lmucs/cher-ami#1]
Was trying to build and run. I also changed `entity.go` to `entity.txt` which didn't help things. It seems that some changes were made between v1 and v2 of go-json-rest. Now http.CloseNotifier is an interface which may have to be implemented by the middleware. This is all based on what I've read on the Github page. 

```
zane@zanes-linux-partition:~/Repos/cher-ami/api/src$ go build main.go 
# github.com/ant0ine/go-json-rest/rest
/usr/lib/go/src/pkg/github.com/ant0ine/go-json-rest/rest/gzip.go:78: undefined: http.CloseNotifier
/usr/lib/go/src/pkg/github.com/ant0ine/go-json-rest/rest/recorder.go:67: undefined: http.CloseNotifier
/usr/lib/go/src/pkg/github.com/ant0ine/go-json-rest/rest/response.go:121: undefined: http.CloseNotifier
```

edit: @rtoal the way you did the example seems to follow v2 guidelines tho

**Comment by ebramanti** [comment]
`main.go` built for me. It's running as well, but we are getting resource errors. Will look into it.

Edit: Really should read code before commenting. Pointed my browser to `posts/0` and I'm getting a successful JSON response.

**Comment by ebramanti** [comment]
Here's _proof_ of what the response looks like, for @AuthorOfTheSurf's reference:

![Response](http://i.imgur.com/H6vgK4l.png)

**Comment by AuthorOfTheSurf** [comment]
dawg, I know what the json response will look like. I can't build the thing. Did `go get` install to the same directory for you? or somewhere in the project directory?

**Comment by ebramanti** [comment]
I added to the TODOS list going over `$GOPATH`, do you have that all set up? Once I set that up my get errors resolved.

**Comment by AuthorOfTheSurf** [comment]
my `$GOPATH` is undefined so it's probably that. Will look at that angle tomorrow morning

**Comment by ebramanti** [comment]
I put it in TODOS, we will go over it tomorrow. 

Here's a link to help out: http://stackoverflow.com/questions/20628918/cannot-download-gopath-not-set

**Comment by AuthorOfTheSurf** [comment]
The real issue was that I was using go version one, 'go1' instead of the recent stable go1.2.

Which exposed the real real issue: that I wasn't using [gvm](https://github.com/moovweb/gvm) to manage my versions...

```
Use gvm, use 1.2
```
