### ISSUE TITLE
Authenticated routes should no longer require "handle" parameters

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [lmucs/cher-ami#14]
The API should be fully converted to discover a user's handle and other required attributes by using the sessionid in the `Authorization` header as a PK. This is currently being done in `NewMessage` as seen here febb716.

This change would be an improvement-of-life for clients since they can more easily call routes with less overall parameters by making use of the required Auth header. Optimized clients could supply the parameter to save the database query though.

**Comment by AuthorOfTheSurf** [comment]
This is currently in progress and will be done today.

**Comment by ebramanti** [comment]
Handle requirement has been removed from most authenticated routes as seen here 31773e2. One route will keep the requirement: `DeleteUser`, where a user must enter their handle, password and be authenticated in order to delete their account.
