### ISSUE TITLE
Make `deps` not working

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [lmucs/cher-ami#17]
`make deps` is not working:
`make: Nothing to be done for "deps"`
I was using tabs in front of the commands and the code nearly identical to `update-deps` which works just fine. weird right?

`make install-test-reqs` could also use another look, I don't know if my npm wasn't configured correctly or if it's something else, it was just exiting with status 0 for me and taking forever. I did use `sudo` to make sure it could do what I needed.

WIP on branch at 2852ba8

**Comment by rtoal** [comment]
There is no `deps` target.  It’s either `install-deps` or `update-deps`.

Also the `install-test-reqs` worked for me.  Open another issue if you can't get it working.

**Comment by ebramanti** [comment]
@AuthorOfTheSurf Next time, run `make help` to be sure if you are entering the right command. It shows available commands to you.

Also, we should talk a little bit about the file structure change, don't know how I feel about `go` folder being changed to `api-server`. Shouldn't it just be `api`?

Maybe we can separate out code for the actual server (a `server` directory) then and have two directories instead.

**Comment by AuthorOfTheSurf** [comment]
`api-server` because we may also have the `web-server` in the same repo at a later point this semester. The `api-server` has an `api` component, but also other components like `routes` and `test`. It's also what it is--an api server, if you just want the api you get `cher-ami/api-server/api` (which is different from the server and part of the point of this). The Go routes will be nicer and more clear this way.

I am not opposed to the `server` directory though. That would be a nice way to show all of the things that the project can host, rather than the web server being mixed in with the api. CORS can be handled, it would be pretty simple to allow requests from a specified server (i.e. the web server).
