### ISSUE TITLE
Support image/video upload in API

### ISSUE THREAD

**Issue by rtoal** [lmucs/cher-ami#6]
We should be able to accept non-text content as uploads.  Put a 1MB or 2MB cap on content.  Store in S3 or maybe CloudFront.  Check with Masao for our AWS keys.  Do not leak the keys to any public repo.  Keep them hidden in config files on a server only.

**Comment by ebramanti** [comment]
I was also thinking we could tie into the Imgur API on the frontend for uploads, and just send a link to the backend for the image and render it on the frontend. We may be able to find a similar solution for video as well.

**Comment by rtoal** [comment]
Imgur is fine to start.  S3 experience will look good on your resume if you can get to it.

**Comment by ebramanti** [comment]
Closing and changing issue above.
