### ISSUE TITLE
Research HTTP PATCH for Marionette

### ISSUE THREAD

**Issue by rtoal** [lmucs/cher-ami#8]
I would like to use the PATCH method in the API but need to know if Marionette can handle it and how.

**Comment by ebramanti** [comment]
@rtoal Yes! Marionette (more precisely, Backbone) is able to use the PATCH method when saving models to the backend. You can read up on it [here](http://backbonejs.org/#Model-save). TL;DR, pass into a model's options that it is a PATCH request. Example:

```
model.save(attrs, {patch: true})
```

**Comment by rtoal** [comment]
Great, thank you, let’s set up a time to code up a prototype.

**Comment by ebramanti** [comment]
PATCH is doable in Marionette and we will have PATCH routes in the API.
