### ISSUE TITLE
Reorganize API docs on the wiki

### ISSUE THREAD

**Issue by rtoal** [lmucs/cher-ami#9]
Currently "API Documentation" is out of date, and "API Wishlist" is evolving into the design we want to use.

Let's move wishlist into the main documentation page and dump the old stuff, but keep whatever is useful if you find anything.

The wishlist page should just be a list of items that would be good to have, without details.  Or we can get rid of that page.

**Comment by AuthorOfTheSurf** [comment]
Opted to drop `API Documentation`, renamed `API Wishlist` to `API Specification` since it isn't realized enough to be considered docs yet

**Comment by rtoal** [comment]
Good choice
